# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('comfortable', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=50)),
                ('classTitle', models.CharField(max_length=50)),
                ('time_start', models.TimeField(blank=True)),
                ('time_end', models.TimeField(blank=True)),
                ('dayOfWeek', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2)),
                ('quarter', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('WI', 'Winter')], max_length=6)),
                ('instructor', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('units', models.IntegerField(default=4)),
                ('spaceLeft', models.IntegerField(blank=True)),
                ('classSize', models.IntegerField(blank=True)),
                ('courseDescription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ManyToManyField(related_name='classes', to='index.Profile'),
        ),
    ]
